version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paymentDB
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
